cas:
  server-url-prefix: http://10.100.254.229:8080/cas
  server-login-url: http://10.100.254.229:8080/cas/login
  client-host-url: http://10.50.20.122:8080
  validation-type: cas

server:
  port: 8080


spring:
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名